name: badges

on:
  schedule:
    # Update badges every 2 minutes
    - cron: '*/20 * * * *'

jobs:
  badges:
    name: Badges
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v4

      - name: Log Before Update version badges ğŸ·
        run: echo "Before npm run badges"

      - name: Update version badges ğŸ·
        run: npm run badges

      - name: Log After Update version badges ğŸ·
        run: echo "After npm run badges"

      - name: Run Cypress tests ğŸš€
        uses: cypress-io/github-action@v2
        with:
          record: true
          key: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Commit any changed files ğŸ’¾
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated badges and ran Cypress tests
          branch: main
          file_pattern: README.md
